apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: sample-api-vpa
  namespace: thesis-demo
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-api
  updatePolicy:
    updateMode: "Initial"
  resourcePolicy:
    containerPolicies:
      - containerName: sample-api
        minAllowed:
          cpu: 100m
          memory: 128Mi
        maxAllowed:
          cpu: 1500m
          memory: 2Gi
        controlledResources: ["cpu", "memory"]
